CREATE TABLE surveys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(5000),
    slug VARCHAR(64) NOT NULL,
    privacy_notice VARCHAR(5000),
    status VARCHAR(16) NOT NULL,
    opened_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_surveys PRIMARY KEY (id),
    CONSTRAINT fk_surveys_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT uk_surveys_slug UNIQUE (slug),
    CONSTRAINT ck_surveys_status CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED'))
);

CREATE INDEX ix_surveys_owner_active_updated
    ON surveys (owner_id, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;
