CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    survey_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(2000),
    required BOOLEAN NOT NULL,
    position INTEGER NOT NULL,
    scale_min INTEGER,
    scale_max INTEGER,
    scale_min_label VARCHAR(100),
    scale_max_label VARCHAR(100),
    number_min NUMERIC(19,4),
    number_max NUMERIC(19,4),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_questions PRIMARY KEY (id),
    CONSTRAINT fk_questions_survey FOREIGN KEY (survey_id) REFERENCES surveys(id),
    CONSTRAINT uk_questions_survey_position UNIQUE (survey_id, position),
    CONSTRAINT ck_questions_type CHECK (
        type IN (
            'SHORT_TEXT',
            'LONG_TEXT',
            'SINGLE_CHOICE',
            'MULTIPLE_CHOICE',
            'SCALE',
            'NUMBER'
        )
    ),
    CONSTRAINT ck_questions_position CHECK (position >= 0),
    CONSTRAINT ck_questions_title CHECK (btrim(title) <> ''),
    CONSTRAINT ck_questions_type_configuration CHECK (
        (
            type IN ('SHORT_TEXT', 'LONG_TEXT', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE')
            AND scale_min IS NULL
            AND scale_max IS NULL
            AND scale_min_label IS NULL
            AND scale_max_label IS NULL
            AND number_min IS NULL
            AND number_max IS NULL
        )
        OR (
            type = 'SCALE'
            AND scale_min IS NOT NULL
            AND scale_max IS NOT NULL
            AND scale_min >= 1
            AND scale_min < scale_max
            AND scale_max <= 10
            AND number_min IS NULL
            AND number_max IS NULL
        )
        OR (
            type = 'NUMBER'
            AND scale_min IS NULL
            AND scale_max IS NULL
            AND scale_min_label IS NULL
            AND scale_max_label IS NULL
            AND (number_min IS NULL OR number_max IS NULL OR number_min <= number_max)
        )
    )
);
CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT NOT NULL,
    label VARCHAR(500) NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT pk_question_options PRIMARY KEY (id),
    CONSTRAINT fk_question_options_question
        FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    CONSTRAINT uk_question_options_question_position UNIQUE (question_id, position),
    CONSTRAINT ck_question_options_position CHECK (position >= 0),
    CONSTRAINT ck_question_options_label CHECK (btrim(label) <> '')
);
