CREATE TABLE survey_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    survey_id BIGINT NOT NULL,
    client_submission_id UUID NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_survey_responses PRIMARY KEY (id),
    CONSTRAINT fk_survey_responses_survey
        FOREIGN KEY (survey_id) REFERENCES surveys(id),
    CONSTRAINT uk_survey_responses_survey_submission
        UNIQUE (survey_id, client_submission_id),
    CONSTRAINT ck_survey_responses_payload_hash
        CHECK (payload_hash ~ '^[0-9a-f]{64}$')
);
