CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    response_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    text_value VARCHAR(5000),
    numeric_value NUMERIC(19,4),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_answers PRIMARY KEY (id),
    CONSTRAINT fk_answers_response
        FOREIGN KEY (response_id) REFERENCES survey_responses(id) ON DELETE CASCADE,
    CONSTRAINT fk_answers_question
        FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE NO ACTION,
    CONSTRAINT uk_answers_response_question UNIQUE (response_id, question_id),
    CONSTRAINT ck_answers_scalar_value
        CHECK (text_value IS NULL OR numeric_value IS NULL)
);

CREATE TABLE answer_options (
    answer_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    CONSTRAINT pk_answer_options PRIMARY KEY (answer_id, option_id),
    CONSTRAINT fk_answer_options_answer
        FOREIGN KEY (answer_id) REFERENCES answers(id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_options_option
        FOREIGN KEY (option_id) REFERENCES question_options(id) ON DELETE NO ACTION
);
