spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:15433}/${DB_NAME:formdock}
    username: ${DB_USERNAME:formdock}
    password: ${DB_PASSWORD}

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      cookie:
        secure: false
